name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_training:
    +materialized: view
    +persist_docs:
      relation: true    # Store model descriptions as table comments in Snowflake
      columns: true     # Store column descriptions as column comments in Snowflake