# models/staging/sources.yml
version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
        description: "Table which contains all deliveries."
      - name: customers
        description: "Table which contains all our customers."
        columns: 
          - name: id
            description: '{{ doc("customer_id") }}'
      - name: orders
        description: "Table that contains all our orders."
        identifier: orders_us  # Use identifier if table's database identifier differs from the source table name