# models/staging/sources.yml
version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: customers
        description: Customer data from our ecommerce application
      - name: orders
        identifier: orders_us

  - name: sheets
    database: raw
    tables:
    - name: customer_survey_responses

