version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: orders
        identifier: orders_us
        description: This record represents the orders of customers
      - name: customers
        description: This record represents the customers
        columns:
          - name: customer_id
            description: '{{ doc("customer_id") }}'

  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses
