version: 2

# models/sources.yml

sources:
  - name: ecomm
    database: raw
    tables:
      - name: customers
        description: "Each record in this table represents a customer in our ecommerce app"
        columns:
          - name: id
            description: '{{doc("customer_id")}}'
      - name: orders
        identifier: orders_us
        description: "Each record in this table represents an order in ouor ecommerce application"
      - name: deliveries
        
      