version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: customers
        description: List of customers
        columns:
          - name: id
            description: '{{ doc("customer_id") }}'
      - name: orders
        description: List of orders
        identifier: orders_us
      
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses