version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: customers
        description: One row per customer
        columns:
          - name: customer_id
            description: "{{ doc('customer_id') }}"
      - name: orders
        identifier: orders_us
        description: One row per order
      
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses