version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: customers
        description: All customers who ordered.
      - name: orders
        identifier: orders_us
        description: All orders send out by all customers.
        columns:
          - name: id
            description: "Unique identifier for each customer."
      
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses