version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: orders
        identifier: orders_us
        description: This record represents the orders of customers
      - name: customers
        description: This record represents a customer
        columns:
          - name: customer_id
            description: This is the corresponding customer id for a customer
      
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses