version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: orders
        identifier: orders_us
        description: All orders placed in the US
        columns:
          - name: updated_at
            description: "{{ doc('updated_at') }}"

      - name: customers
        description: Information on the customers addresses, names, etc
        columns: 
          - name: customer_id
            description: This is the column containing a unique identifier on the customer name
      
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses