version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: customers
        description: Each record represents a customer.
        columns:
          - name: customer_id
            description: '{{ doc("customer_id") }}'
          - name: first_name
            description: A customer's first name.
          - name: last_name
            description: A customer's last name.
          - name: count_orders
            description: The number of orders a customer has had all-time.
          - name: first_order_at
            description: The timestamp of a customer's first order.
          - name: most_recent_order_at
            description: The timestamp of a customer's most recent order.
      - name: orders
        description: Contains all customer orders, enriched with delivery times and status
        identifier: orders_us

  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses
